# Generated by Django 2.2.2 on 2019-06-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import courses.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in USD')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateField()),
                ('is_enroll_open', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', courses.fields.OrderField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('url', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('content', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='Specify 0 for unlimited attempts.')),
                ('paid_only', models.BooleanField(default=False, help_text='True if available only to users who bought a course.')),
                ('answer', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringassignment_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringassignment_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoicesAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='Specify 0 for unlimited attempts.')),
                ('paid_only', models.BooleanField(default=False, help_text='True if available only to users who bought a course.')),
                ('_choices', models.TextField()),
                ('_correct_choices', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplechoicesassignment_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplechoicesassignment_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.Module'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('file', models.ImageField(upload_to='images')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('file', models.FileField(upload_to='files')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses_teaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChoicesAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', courses.fields.OrderField(blank=True)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='Specify 0 for unlimited attempts.')),
                ('paid_only', models.BooleanField(default=False, help_text='True if available only to users who bought a course.')),
                ('_choices', models.TextField()),
                ('answer', models.CharField(max_length=80)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicesassignment_related', to='courses.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicesassignment_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['content_type', 'id'], name='courses_vid_content_c23342_idx'),
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['content_type', 'id'], name='courses_tex_content_e16de9_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['content_type', 'id'], name='courses_ima_content_5b9c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_type', 'id'], name='courses_fil_content_9c0453_idx'),
        ),
    ]
