# Generated by Django 2.1.3 on 2019-06-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='assignment_content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='item_content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='choicesassignment',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choicesassignment_related', to='courses.Assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to='courses.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to='courses.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicesassignment',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multiplechoicesassignment_related', to='courses.Assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stringassignment',
            name='assignment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stringassignment_related', to='courses.Assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to='courses.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to='courses.Item'),
            preserve_default=False,
        ),
    ]
