# Generated by Django 2.2.2 on 2019-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesassignment',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='multiplechoicesassignment',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='stringassignment',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
    ]
