# Generated by Django 2.1.3 on 2019-06-25 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='text',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
