# Generated by Django 2.2.3 on 2019-07-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190630_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesassignment',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='multiplechoicesassignment',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='stringassignment',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
