# Generated by Django 2.1.3 on 2019-06-25 11:21

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190625_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='order',
            field=courses.fields.OrderField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=courses.fields.OrderField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='order',
            field=courses.fields.OrderField(blank=True, default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=courses.fields.OrderField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
